### ISSUE TITLE
add tutorials on customizing your environment

### ISSUE THREAD

**Issue by JessicaS11** [CryoInTheCloud/CryoCloudWebsite#59]
In advance of the FOGSS tutorial, we needed to do a lot of working with in-progress branches of libraries that come on the hub. Installing these dev versions was non-trivial and there were a lot of issues getting the correct versions of software going. We ended up creating a lot of tutorial content that outlined this process for users. I suggest we create a short "how-to" guide with a set of links to the 2i2c and Jupyter docs that explain how to do this.

**Comment by tsnow03** [comment]
Was this sufficiently covered in this new text: https://book.cryointhecloud.com/how_tos/background/python.html?
